name: open_microwave
cameras:
  - "front_camera"
  - "wrist_camera"
proprio_dim: 14
action_horizon: 10
action_dim: 7
action_shape:
  - ${task.action_horizon}
  - ${task.action_dim}
env:
  _target_: icon.envs.rlbench.RLBenchEnv
  task: ${task_name}
  cameras: ${task.cameras}
  image_size: ${algo.policy.obs_encoder.image_encoder.img_size}
  robot: "panda"
  arm_controller: "ee_delta_pose"
  headless: True