name: open_box
num_cameras: 2
cameras:
  - 'front_camera'
  - 'wrist_camera'
shape_meta:
  images: 256
  low_dims: 14
  actions: 7
# env:
#   _target_: icon.envs.rlbench.RLBenchEnv
#   task: ${task_name}
#   cameras: ${task.cameras}
#   image_size: ${algo.policy.obs_encoder.image_encoder.img_size}
#   robot: "panda"
#   arm_controller: "ee_delta_pose"
#   headless: True