train:
  _target_: torch.utils.data.DataLoader
  batch_size: ${train.batch_size}
  shuffle: true
  num_workers: 0
  pin_memory: true
  drop_last: false

val:
  _target_: torch.utils.data.DataLoader
  batch_size: ${train.batch_size}
  shuffle: false
  num_workers: 0
  pin_memory: true
  drop_last: false
