train_loader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: icon.utils.dataset.EpisodicDataset
    episode_dir: ${train.dataset_dir}/train
    cameras: ${task.cameras}
    action_horizon: ${task.action_horizon}
    norm_modes: 
      proprios: "max_min"
      actions: "max_min"
    load_masks: true
    transform_cfg:
      resize_shape: 256
      crop_shape: 224
      random_crop: true
      enable_imagenet_norm: false

  batch_size: ${train.batch_size}
  shuffle: true
  num_workers: 16
  pin_memory: true
  drop_last: false

val_loader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: icon.utils.dataset.EpisodicDataset
    episode_dir: ${train.dataset_dir}/val
    cameras: ${task.cameras}
    action_horizon: ${task.action_horizon}
    norm_modes: 
      proprios: "max_min"
      actions: "max_min"
    load_masks: false
    transform_cfg:
      resize_shape: 256
      crop_shape: 224
      random_crop: false
      enable_imagenet_norm: false

  batch_size: ${train.batch_size}
  shuffle: false
  num_workers: 16
  pin_memory: true
  drop_last: false