defaults:
  - _self_
  - task: close_drawer
  - algo: icon
  - train: ${algo}
  - env: rlbench

_target_: icon.workspaces.workspace.WorkSpace

task_name: ${task.name}
algo_name: ${algo.name}

hydra:
  run:
    dir: outputs/${task_name}/${algo_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
