name: raw
policy:
  _target_: icon.policies.diffusion_policy.DiffusionPolicy

  obs_encoder:
    _target_: icon.models.obs_encoder.ObsEncoder
    cameras: ${task.cameras}
    proprio_dim: ${task.proprio_dim}
    embed_dim: ${algo.policy.noise_predictor.embed_dim}
    image_encoder:
      _target_: icon.models.obs_encoder.ViT
      patch_size: 16
      embed_dim: 384
      depth: 12
      num_heads: 6  

  noise_predictor:
    _target_: icon.models.diffusion.TransformerForDiffusion
    obs_cond_horizon: 3
    action_shape: ${task.action_shape}
    embed_dim: 256
    num_heads: 4
    num_encoder_layers: 0
    num_decoder_layers: 8
    causal_attn: true

  noise_scheduler:
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: 100
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: "squaredcos_cap_v2"
      clip_sample: true
      prediction_type: "epsilon"

  action_shape: ${task.action_shape}
  num_inference_timesteps: 8