defaults:
  - _self_
  - dataset: ae
  - dataloader: default

seed: 42
device: "cuda:6"
batch_size: 64
num_epochs: 600
dataset_root_dir: data/${task_name}

val:
  enable: true
  ckpt_manager:
    _target_: icon.utils.file_utils.CheckpointManager
    save_dir: outputs/${task_name}/${algo_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/checkpoints
    val_freq: 100
    topk: 5
    mode: "min"
    save_last: true

optimizer:
  lr: 1e-4
  obs_encoder_weight_decay: 1e-6
  noise_predictor_weight_decay: 1e-3
  betas:
    - 0.9
    - 0.95
  
lr_scheduler:
  _target_: icon.utils.train_utils.get_scheduler
  name: "cosine"
  num_warmup_steps: 500

ema:
  enable: true
  runner:
    _target_: icon.utils.train_utils.EMA
    update_after_step: 0
    inv_gamma: 1.0
    power: 0.75
    min_value: 0.0
    max_value: 0.9999

wandb:
  enable: false
  logging:
    project: "policy_training"
    resume: True
    mode: online
    name: ${task_name}_${algo_name}_${now:%Y.%m.%d-%H.%M.%S}
    tags:
      - ${task_name}
      - ${algo_name}
    id: null
    group: null